title: Hackathon
email: p.bauer@htl-leonding.ac.at
description: > # this means to ignore newlines until "baseurl:"
  Sharpen your coding skills in this hackathon.
url: "https://bauepete.github.io/GitHubEduWorkshop-Jekyll"
github_username:  bauepete
baseurl: /GitHubEduWorkshop-Jekyll
